create table if not exists public.ticket_notifications (
  id bigint generated by default as identity primary key,
  recipient_id text not null,
  ticket_id text not null,
  title text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.ticket_notifications enable row level security;
drop policy if exists "Notifications can be read" on public.ticket_notifications;
drop policy if exists "Notifications can be created" on public.ticket_notifications;
drop policy if exists "Notifications can be marked read" on public.ticket_notifications;
create policy "Notifications can be read" on public.ticket_notifications for select to anon using (true);
create policy "Notifications can be created" on public.ticket_notifications for insert to anon with check (true);
create policy "Notifications can be marked read" on public.ticket_notifications for update to anon using (true) with check (true);
